Shared Element Transitions for Modals!
wix/react-native-navigation pull request #6625
Opened 2020-09-30 09:16 UTC by mrousavy

This PR adds support for running Shared Element Transitions with `showModal` and `dismissModal` operations. By design, this also includes any animations (including element transitions, content animations, etc.) that are included in Stack operations (`push`, `pop` and `setStackRoot`)

Currently WIP, and iOS only

2020-09-30 11:32 UTC, mrousavy commented
Does it make more sense to give the `showModal` and `dismissModal` commands their own transitioning delegate back instead of re-using the `StackTransitioningDelegate` from `push`/`pop` commands? I can't seem to get the transitioning delegate to run it's animations, not sure why..

2020-10-02 16:09 UTC, mrousavy commented
At the current state the Shared Element Transitions work for Modals on iOS. 🥳  I've noticed two "regressions" though:

1. The Shared Elements don't start at a scaled down state (applied through transform), so instead a short flicker is noticeable.
2. The FastImage `borderRadius` transitions don't seem to work anymore.

Both of those are not always happening, and it seems like they're mutually exclusive bugs, in other words; If **1.** works, **2.** doesn't work and vice versa.

@guyca I'll take a look if I can implement Android myself, if not, I'll have to wait for you to come back from vacation/guild week. 🏖️

2020-10-03 18:35 UTC, guyca commented
@mrousavy This sounds amazing! Can't wait to get back from my staycation! 💪

2020-10-06 10:35 UTC, mrousavy commented
I can't work on the Android implementation right now because I got some refactoring to do for my app. I'm already using modals for SETs in my app, so Android just doesn't work atm, meaning it's pretty high priority for me so I'll take another look at it once I got my refactoring finished 😄 

About the two iOS issues; Looks like we already had something similar before (https://github.com/wix/react-native-navigation/pull/6603, https://github.com/wix/react-native-navigation/pull/6563, ...)

2020-10-11 09:38 UTC, yogevbd commented
@mrousavy I do think we should wait for a major release if it contains a breaking change, even though it's a minor change.. @guyca wdyt?

2020-10-11 12:41 UTC, guyca requested changes

2020-10-11 12:41 UTC, guyca commented on lib/src/commands/OptionsProcessor.test.ts
> +      animations: { dismissModal: { content: { alpha: { from: 0, to: 1 } } } },
@mrousavy Modals don't have a content property. When declaring modal animations, the entire view of the modal is animated.

content is used to declare animations that operate on the views pushed into a stack.

We should keep the current API unchanged.

2020-10-11 12:43 UTC, guyca commented
Nice catch @yogevbd !
@mrousavy I commented on the api change 👍

2020-10-18 09:55 UTC, guyca requested changes

2020-10-18 09:55 UTC, guyca commented on lib/src/interfaces/Options.ts
> +  showModal?: StackAnimationOptions;
@mrousavy This change should be reverted as well 👍

2020-10-18 09:55 UTC, guyca commented on playground/src/screens/sharedElementCarDealer/CarDetailsScreen.tsx
> +    Navigation.dismissModal(componentId);
You've changed the cars example to use modals? Nice!

2020-10-20 07:04 UTC, yogevbd approved these changes

2020-10-20 07:04 UTC, merged