Refactor buttons, add button styling options
wix/react-native-navigation pull request #6851
Opened 2020-12-21 23:17 UTC by yogevbd

* Refactor buttons creation flow.
* Add button with icon styling options
  * `cornerRadius`
  * `backgroundColor`
  * `width`
  * `height`

We should consider adding those styles to any button type.

2020-12-23 08:33 UTC, mrousavy commented
Does this use `RCTText` or are you manually applying styles?

2020-12-23 13:56 UTC, yogevbd commented
@mrousavy it's not related to the title text, only to the icon background.

2020-12-23 16:07 UTC, guyca requested changes

2020-12-23 16:52 UTC, yogevbd commented on lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/IconBackgroundDrawable.kt
> +        return UiUtils.dpToPx(context, getBackgroundWidth())
Removed this function as it's no longer needed

2020-12-23 16:53 UTC, yogevbd commented on lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/IconBackgroundDrawable.kt
> +    override fun getIntrinsicHeight(): Int {
Removed this function as it's no longer needed

2020-12-23 16:53 UTC, yogevbd commented on lib/ios/RNNButtonsPresenter.m
> +- (RNNUIBarButtonItem *)buildButton:(RNNButtonOptions *)button {
done

2020-12-23 16:54 UTC, yogevbd commented on lib/android/app/src/main/java/com/reactnativenavigation/options/IconBackgroundOptions.java
> +        return color.hasValue() ||
Color should be mandatory, width and height can have the default icon size

2020-12-24 08:54 UTC, guyca requested changes

2020-12-24 08:54 UTC, guyca commented on lib/ios/RNNButtonBuilder.m
> +    [self assertButtonId:button];
Typically, a caller function should be placed above the callee. High-level functions are placed above low-level functions.

2020-12-24 08:54 UTC, guyca commented on lib/ios/RNNButtonBuilder.m
> +- (void)bindViewController:(UIViewController<RNNLayoutProtocol> *)viewController {
The builder pattern is used in direct substitution to a class' constructor, therefore all parameters the constructor requires should be available. Using a method prefixed with `bind` sounds foreign here.

Let's rename it to `setViewController` and have the method return the builder, this way we can chain its invocation with the `build()` method.

2020-12-24 09:15 UTC, yogevbd commented on lib/android/app/src/main/java/com/reactnativenavigation/options/IconBackgroundOptions.java
> +        return color.hasValue() &&
No, it falls back to the original icon size

2020-12-24 10:18 UTC, guyca approved these changes

2020-12-24 14:33 UTC, merged