Shared element android fix
wix/react-native-navigation pull request #7081
Opened 2021-04-11 14:18 UTC by swabbass

# Issue

Showing modal with shared element transition broke, in the opening direction, while it is working in the closing direction, like when opening a card in the Car dealer in the Playground, the shared card won't animate to the new position, fading instead.

https://user-images.githubusercontent.com/7227793/114307698-7cfdd700-9ae9-11eb-8f4c-d4ca4235e9db.mov

# Fix

Check and test that SharedElement transition is playing, matching `push` shared element behaviour, making `showModal` and `push` aligned since push does not suffer such misbehaving in shared element.

https://user-images.githubusercontent.com/7227793/114307791-c2ba9f80-9ae9-11eb-9068-8931a8238994.mov

Closes: #7070

2021-04-13 07:57 UTC, guyca requested changes

2021-04-13 07:57 UTC, guyca commented on lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalAnimator.kt
> -                runningAnimators[appearing] = animation
This isn't needed anymore?

2021-04-13 11:51 UTC, swabbass commented on lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalAnimator.kt
> -                runningAnimators[appearing] = animation
moved to the `show` function.

2021-04-14 04:35 UTC, guyca approved these changes

2021-04-14 04:36 UTC, merged