Add SF Symbols support to bottom tab and top bar's back button
wix/react-native-navigation pull request #7271
Opened 2021-09-23 14:20 UTC by svbutko

Since SF Symbols are built in starting from iOS 13 it makes sense to use them as icons rather than creating PNGs which will increase app size.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/14828004/134523928-2a5d19ff-a42a-445e-abf7-d4d64d222025.png">

<img width="502" alt="image" src="https://user-images.githubusercontent.com/14828004/134523961-24a521b1-bb69-43c6-9324-c91b64a4342c.png">

2021-09-29 08:21 UTC, yogevbd approved these changes

2021-09-29 16:08 UTC, svbutko commented
Test are failing correctly since SF Symbols are supported starting from iOS 13 and I did `available` checks but still this tests are running

2021-10-04 13:29 UTC, yogevbd requested changes

2021-10-04 15:39 UTC, svbutko commented
@yogevbd, fixed the issue with tests

2021-10-04 16:51 UTC, yogevbd approved these changes

2021-10-04 16:51 UTC, merged